### PR TITLE
Formatting cleanup

### PR DESCRIPTION
**Pull request by djmetzle**
There were some ugly whitespace problems that were irking. Fix em!

cr_req 1
qa_req 0 (literally only whitespace)

CC @danielbeardsley @andyg0808

### CODE REVIEW

**Comment by andyg0808** [comment]
CR :+1: through 897e2cf

**Comment by danielbeardsley** [comment]
CR 👍

**Comment by djmetzle** [comment]
Wait!

**Comment by djmetzle** [comment]
More whitespace fixes!

**Comment by djmetzle** [comment]
image

QA :smile:

**Comment by andyg0808** [comment]
CR :+1: through ed74aa6

**Comment by danielbeardsley** [comment]
CR 👍 
I didn't change it, I just did `git commit --amend` so it'd get a new hash and re-run the travis builds

**Comment by andyg0808** [comment]
CR :+1: through f89785d

**Comment by djmetzle** [comment]
image

QA :gear:

**Pull request merged**
